### ISSUE TITLE
Implement Scheduler API JSON types

### ISSUE THREAD

**Issue by oubiwann** [clojusc/meson#28]
The scheduler API protobuf types are likely already available due to the copy from Mesomatic. However, they may not be organized properly into an appropriate namespace. 

Also, there may need to be a base-level, general-use namespace for protobuf types and/or related code that will be usable by all API protobufs (that is now its own ticket: #29)

**Comment by wdhowe** [comment]
I believe this is complete due to the API json types being defined via the [IScheduler protocol](https://github.com/clojusc/meson/blob/master/src/meson/protocols/master/scheduler.clj) and [extended in the client](https://github.com/clojusc/meson/blob/master/src/meson/client/master.clj)?

**Comment by oubiwann** [comment]
Excellent!
