### ISSUE TITLE
Create example unit, integration, and system tests

### ISSUE THREAD

**Issue by billota** [clojusc/meson#39]
This will utilize the new Mesos testing infrastructure.

Depends upon:
- #37
- #38 

Tasks:
- [x] Update existing unit tests with `^unit` annotations.
- [x] Create a working integration test

Skipping:
- Create a working sample system test
#### Background

We are using the following definitions (from the Wikipedia article on [Software Testing](https://en.wikipedia.org/wiki/Software_testing#Testing_levels)):
- Unit Tests - verify the functionality of a specific section of code
- Integration Tests - verify the interfaces between components against a software design
- System Tests - verify that the complete system -- software, dependencies, services -- meets its operational requirements

**Comment by hromagnum** [comment]
To do the system test, we'll need a Mesos v1.0 framework, so we'll open a separate ticket for that.

**Comment by hromagnum** [comment]
Added #48 to complete the skipped item in the description.

**Comment by hromagnum** [comment]
Done.
